language: csharp
mono: none
dotnet: 2.0.0
dist: xenial
script:
 - dotnet restore
 - dotnet build -c Release ./src/Anvyl.JsonLocalizer/Anvyl.JsonLocalizer.csproj
 - dotnet test ./test/Anvyl.JsonLocalizer.Tests/Anvyl.JsonLocalizer.Tests.csproj